"""Hand transcription of master-map annotations. Not generated."""

# Each item: text, approx pixel (x,y) of the pointed room/feature, confidence,
# category, geometric / visual / gameplay notes.
# Confidence: HIGH | MEDIUM | LOW | UNREADABLE
# Pixel coords are on the 3800x3700 master PNG (origin top-left).

ANNOTATIONS = [
    # NW
    {"id": "A001", "text": "Unexplored... how much further can I go?", "px": [180, 80], "confidence": "HIGH", "category": "unknown", "geom": "dead-end corridor continues off-map north-west", "visual": "dotted unexplored continuation", "gameplay": "do not invent an exit"},
    {"id": "A002", "text": "Line of posters - Closing down sale", "px": [210, 280], "confidence": "HIGH", "category": "props", "geom": None, "visual": "posters on wall", "gameplay": "CONTENT_REQUIRED prop, skip in pilot"},
    {"id": "A003", "text": "These walls stop short of the ceiling", "px": [430, 390], "confidence": "HIGH", "category": "architecture", "geom": "partition walls shorter than 3 m", "visual": "gap to ceiling", "gameplay": None},
    {"id": "A004", "text": "Tall room - unreachable doors in wall near roof", "px": [620, 160], "confidence": "HIGH", "category": "architecture", "geom": "ceiling ~6-8 m; high door openings not reachable", "visual": "tall volume", "gameplay": "no crouch/climb system yet"},
    {"id": "A005", "text": "This area seems like a normal house", "px": [720, 520], "confidence": "HIGH", "category": "special_rooms", "geom": "house-like rooms, different furniture density", "visual": "domestic layout, salmon interior", "gameplay": "not a wiki Object"},
    {"id": "A006", "text": "Lift - buttons are numbered irregularly (1,3, B8, R, 13)", "px": [820, 500], "confidence": "HIGH", "category": "architecture", "geom": "elevator cab + shaft if built", "visual": "lift", "gameplay": "CONTENT_REQUIRED; do not invent destinations"},
    {"id": "A007", "text": "Very tall ceiling in this room", "px": [1180, 280], "confidence": "HIGH", "category": "verticality", "geom": "ceiling 6 m+", "visual": "tall", "gameplay": None},
    {"id": "A008", "text": "These rooms remind me of my grandma's basement - low ceiling, concrete walls, musty", "px": [1280, 280], "confidence": "HIGH", "category": "architecture", "geom": "low ceiling ~2.1 m, concrete", "visual": "musty concrete", "gameplay": None},
    {"id": "A009", "text": "Plywood copy of the Resolute Desk", "px": [1680, 420], "confidence": "HIGH", "category": "props", "geom": None, "visual": "desk prop", "gameplay": "CONTENT_REQUIRED prop"},
    {"id": "A010", "text": "Poster for a fish spa", "px": [1480, 560], "confidence": "HIGH", "category": "props", "geom": None, "visual": "poster", "gameplay": "CONTENT_REQUIRED prop"},
    {"id": "A011", "text": "I can't explain it, but this room feels like a church", "px": [1100, 700], "confidence": "HIGH", "category": "special_rooms", "geom": "pew-like furniture rows", "visual": "church feeling", "gameplay": None},
    {"id": "A012", "text": "These halls shouldn't be able to meet in this room. There are several more staircases on the right entrance than the left. There should be several floors difference between them", "px": [1980, 220], "confidence": "HIGH", "category": "verticality", "geom": "non-Euclidean note; stair counts differ L/R; do not force same Y", "visual": "multiple stairs into one room", "gameplay": "flag spatial anomaly; do not invent noclip"},
    {"id": "A013", "text": "Hotel room? Bed way too short", "px": [2180, 380], "confidence": "HIGH", "category": "special_rooms", "geom": "small hotel-like room", "visual": "short bed", "gameplay": "CONTENT_REQUIRED prop"},
    {"id": "A014", "text": "Pool tables - baize makes my skin itch", "px": [2480, 280], "confidence": "HIGH", "category": "props", "geom": "two green tables", "visual": "green baize", "gameplay": "no status effect invented"},
    {"id": "A015", "text": "Doors stuck", "px": [2100, 620], "confidence": "HIGH", "category": "openings", "geom": "blocked door pair, no passage", "visual": "stuck doors", "gameplay": "not a usable door"},
    {"id": "A016", "text": "Furniture facing wall?", "px": [2580, 80], "confidence": "HIGH", "category": "props", "geom": None, "visual": "misoriented furniture", "gameplay": None},
    {"id": "A017", "text": "unexplored", "px": [2720, 60], "confidence": "HIGH", "category": "unknown", "geom": "dotted continuation", "visual": None, "gameplay": None},
    {"id": "A018", "text": "Classroom?", "px": [2580, 480], "confidence": "HIGH", "category": "special_rooms", "geom": "desks in rows", "visual": "pink adjacent cluster", "gameplay": None},
    {"id": "A019", "text": "This place makes we feel sick", "px": [2580, 620], "confidence": "HIGH", "category": "hazards", "geom": "pink/red cluster", "visual": "sickly pink rooms", "gameplay": "canon conflict: map Red rooms vs wiki Red Rooms; CONTENT_REQUIRED; no meeting zone"},
    {"id": "A020", "text": "I thought this grey carpet was patterned, but the design never repeats", "px": [3000, 160], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "grey carpet, non-repeating", "gameplay": None},
    {"id": "A021", "text": "This whole wall is windows. There's a whole city out there... Why is the sun red?", "px": [3300, 180], "confidence": "HIGH", "category": "architecture", "geom": "window wall on large grey hall", "visual": "windows; do NOT render a canon outdoor city", "gameplay": "canon conflict: Level 0 has no exterior; fake windows only"},
    {"id": "A022", "text": "Blue carpet - reminds me of a hotel", "px": [3300, 620], "confidence": "HIGH", "category": "surface", "geom": "blue-grey hotel wing", "visual": "blue carpet", "gameplay": None},
    # west / mid
    {"id": "A023", "text": "Very irregularly shaped rooms in this area", "px": [220, 820], "confidence": "HIGH", "category": "geometry", "geom": "keep irregular silhouette, no rect merge", "visual": None, "gameplay": None},
    {"id": "A024", "text": "Dark hallways", "px": [250, 1100], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "few/no fixtures", "gameplay": "local poor lighting"},
    {"id": "A025", "text": "Stop sign", "px": [620, 1120], "confidence": "HIGH", "category": "props", "geom": None, "visual": "red sign", "gameplay": "CONTENT_REQUIRED prop"},
    {"id": "A026", "text": "This room exhausted me felt like climbing a steep slope", "px": [700, 980], "confidence": "HIGH", "category": "verticality", "geom": "sloped floor", "visual": None, "gameplay": "no stamina-lore; geometry slope only"},
    {"id": "A027", "text": "Mannequin here - scared the hell out of me", "px": [720, 1280], "confidence": "HIGH", "category": "props", "geom": None, "visual": "mannequin", "gameplay": "NOT an Entity; Level 0 entities unconfirmed; skip AI"},
    {"id": "A028", "text": "More fake windows. These ones are painted on", "px": [1180, 900], "confidence": "HIGH", "category": "architecture", "geom": None, "visual": "painted window fake", "gameplay": None},
    {"id": "A029", "text": "Very weird wall arrangements", "px": [1280, 1180], "confidence": "HIGH", "category": "architecture", "geom": "irregular interior walls", "visual": None, "gameplay": None},
    {"id": "A030", "text": "Framed painting on wall - but painting is printed right onto wall", "px": [1320, 1100], "confidence": "HIGH", "category": "props", "geom": None, "visual": "printed painting", "gameplay": None},
    {"id": "A031", "text": "Sign on the wall here: \"All must go.\"", "px": [1680, 1000], "confidence": "HIGH", "category": "props", "geom": None, "visual": "sign", "gameplay": None},
    {"id": "A032", "text": "Huge interconnected rooms", "px": [1900, 780], "confidence": "HIGH", "category": "geometry", "geom": "large open linked rooms", "visual": None, "gameplay": None},
    {"id": "A033", "text": "room with weird pillars", "px": [1980, 980], "confidence": "HIGH", "category": "architecture", "geom": "real columns on a grid-like field", "visual": "pillars", "gameplay": "wiki pillar variation compatible"},
    {"id": "A034", "text": "Red rooms", "px": [2360, 780], "confidence": "HIGH", "category": "hazards", "geom": "pink/red cluster", "visual": "red/pink", "gameplay": "wiki Red Rooms: dangerous, avoid; NOT a meeting zone; CONTENT_REQUIRED"},
    {"id": "A035", "text": "Rooms all totally empty", "px": [2220, 980], "confidence": "HIGH", "category": "props", "geom": None, "visual": "empty", "gameplay": None},
    {"id": "A036", "text": "Bookshelves - All books have blank pages", "px": [1760, 1120], "confidence": "HIGH", "category": "props", "geom": None, "visual": "bookshelves", "gameplay": "CONTENT_REQUIRED prop"},
    {"id": "A037", "text": "Carpet changes", "px": [1720, 1280], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "carpet variant boundary", "gameplay": None},
    {"id": "A038", "text": "Can't unblock", "px": [1580, 1280], "confidence": "HIGH", "category": "openings", "geom": "blocked passage", "visual": "furniture jam", "gameplay": None},
    {"id": "A039", "text": "Well furnished area / current base", "px": [1500, 1280], "confidence": "HIGH", "category": "special_rooms", "geom": "furnished rooms", "visual": "base camp furniture", "gameplay": "Isolation Effect: no other players visible; geometry of a camp is allowed"},
    {"id": "A040", "text": "bathroom with safe water", "px": [1620, 1380], "confidence": "HIGH", "category": "water", "geom": "bathroom + basin water", "visual": "water present", "gameplay": "canon conflict: wiki carpet fluids/Almond Water tainted; do NOT make drinkable"},
    {"id": "A041", "text": "block entryway with cupboard", "px": [1420, 1420], "confidence": "HIGH", "category": "openings", "geom": "blocked door", "visual": "cupboard", "gameplay": None},
    {"id": "A042", "text": "Carpet soaked through here", "px": [2360, 980], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "wet carpet darker", "gameplay": "no disease invented"},
    {"id": "A043", "text": "Flickering lights", "px": [2680, 860], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "local flicker fixtures", "gameplay": None},
    {"id": "A044", "text": "100s of wires hanging from ceiling", "px": [2620, 1040], "confidence": "HIGH", "category": "architecture", "geom": None, "visual": "hanging wires", "gameplay": "CONTENT_REQUIRED prop"},
    {"id": "A045", "text": "Pile of clothes", "px": [2860, 1100], "confidence": "HIGH", "category": "props", "geom": None, "visual": "clothes pile", "gameplay": None},
    {"id": "A046", "text": "Very loud lights", "px": [2480, 1140], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "brighter/harsher fixtures", "gameplay": "wiki noise spikes; no hearing damage system"},
    {"id": "A047", "text": "Tiny red room?", "px": [2420, 1220], "confidence": "HIGH", "category": "hazards", "geom": "tiny pink cubicle", "visual": "red", "gameplay": "possible Red Room fragment; CONTENT_REQUIRED"},
    {"id": "A048", "text": "Loads of chairs", "px": [2280, 1200], "confidence": "HIGH", "category": "props", "geom": None, "visual": "many chairs", "gameplay": None},
    {"id": "A049", "text": "Desk full of pens", "px": [2720, 1200], "confidence": "HIGH", "category": "props", "geom": None, "visual": "desk", "gameplay": None},
    {"id": "A050", "text": "Kitchen with canned food", "px": [2280, 1360], "confidence": "HIGH", "category": "props", "geom": None, "visual": "kitchen", "gameplay": "do not invent hunger restore"},
    {"id": "A051", "text": "Writing on wall: \"156m - 79st\"", "px": [2100, 1380], "confidence": "HIGH", "category": "props", "geom": None, "visual": "graffiti", "gameplay": None},
    {"id": "A052", "text": "Furnished rooms", "px": [2780, 1380], "confidence": "HIGH", "category": "special_rooms", "geom": None, "visual": "green-tinted furnished", "gameplay": None},
    {"id": "A053", "text": "Smashed and broken tables and chairs", "px": [3120, 1280], "confidence": "HIGH", "category": "props", "geom": None, "visual": "debris", "gameplay": None},
    {"id": "A054", "text": "Room almost pitch black", "px": [3500, 900], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "no fixtures, blackout", "gameplay": "wiki blackout zone compatible"},
    {"id": "A055", "text": "Weirdly tall chairs", "px": [3280, 1280], "confidence": "HIGH", "category": "props", "geom": "oversized chairs if built", "visual": "tall chairs", "gameplay": None},
    {"id": "A056", "text": "Crashed car in this room - came through the ceiling?", "px": [3180, 1480], "confidence": "HIGH", "category": "architecture", "geom": "ceiling hole + car volume", "visual": "car, ceiling breach", "gameplay": "CONTENT_REQUIRED; not an exit"},
    {"id": "A057", "text": "Almost normal decor in these rooms", "px": [3480, 1480], "confidence": "HIGH", "category": "props", "geom": None, "visual": "ordinary furniture", "gameplay": None},
    {"id": "A058", "text": "Room full of sofas", "px": [3180, 1620], "confidence": "HIGH", "category": "props", "geom": None, "visual": "many sofas, reddish", "gameplay": None},
    {"id": "A059", "text": "Tiny crack - I hear bird song and smell grass", "px": [3680, 1720], "confidence": "HIGH", "category": "unknown", "geom": "hairline opening, not walkable", "visual": "crack", "gameplay": "do not invent an exit/Level"},
    # west lower-mid
    {"id": "A060", "text": "Tiny table with loads of chairs", "px": [720, 1380], "confidence": "HIGH", "category": "props", "geom": None, "visual": "table+chairs cluster", "gameplay": None},
    {"id": "A061", "text": "Extreme water damage in these rooms", "px": [480, 1580], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "stained/wet walls and carpet", "gameplay": None},
    {"id": "A062", "text": "Steeply sloping floor", "px": [620, 1680], "confidence": "HIGH", "category": "verticality", "geom": "sloped floor", "visual": None, "gameplay": None},
    {"id": "A063", "text": "Chair half stuck in ground", "px": [900, 1380], "confidence": "HIGH", "category": "props", "geom": "chair intersecting floor", "visual": None, "gameplay": None},
    {"id": "A064", "text": "Intercom endlessly repeating \"Mind the gap\" on wall here", "px": [980, 1680], "confidence": "HIGH", "category": "props", "geom": None, "visual": "intercom", "gameplay": "CONTENT_REQUIRED audio; skip in pilot"},
    {"id": "A065", "text": "Weird black substance on floor here", "px": [1280, 1480], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "black stain", "gameplay": "do not invent infection"},
    {"id": "A066", "text": "Mummified rat", "px": [1280, 1680], "confidence": "HIGH", "category": "props", "geom": None, "visual": "dead rat", "gameplay": "not an Entity"},
    {"id": "A067", "text": "Felt like I was being watched here", "px": [1280, 1820], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": None, "gameplay": "wiki scopophobia reports; no Entity spawn"},
    {"id": "A068", "text": "tiled / Bottomless pool", "px": [1320, 1580], "confidence": "HIGH", "category": "hazards", "geom": "square pool, no floor, tiled rim, black shaft", "visual": "blue square, void below", "gameplay": "wiki holes: do not survive a fall; shaft not an exit"},
    {"id": "A069", "text": "very tall room", "px": [1620, 1720], "confidence": "HIGH", "category": "verticality", "geom": "ceiling ~6-8 m", "visual": "tall", "gameplay": None},
    {"id": "A070", "text": "Safe water!", "px": [2100, 1680], "confidence": "HIGH", "category": "water", "geom": "small basin/water", "visual": "water", "gameplay": "canon conflict vs wiki; geometry only, not drinkable"},
    {"id": "A071", "text": "balcony", "px": [1980, 1680], "confidence": "HIGH", "category": "verticality", "geom": "balcony overlooking lower space", "visual": None, "gameplay": None},
    {"id": "A072", "text": "Different carpet here!", "px": [2080, 1720], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "carpet variant", "gameplay": None},
    {"id": "A073", "text": "Bedroom", "px": [2280, 1780], "confidence": "HIGH", "category": "special_rooms", "geom": None, "visual": "bed", "gameplay": None},
    {"id": "A074", "text": "pool table", "px": [2260, 1620], "confidence": "HIGH", "category": "props", "geom": None, "visual": "green table", "gameplay": None},
    {"id": "A075", "text": "Rooms with wooden floors", "px": [2380, 1680], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "brown wood", "gameplay": None},
    {"id": "A076", "text": "Green rooms (leafy wallpaper)", "px": [2680, 1580], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "green wallpaper/carpet", "gameplay": None},
    {"id": "A077", "text": "Pipes/vents all over walls", "px": [2920, 1680], "confidence": "HIGH", "category": "architecture", "geom": None, "visual": "pipes", "gameplay": None},
    {"id": "A078", "text": "Concrete area", "px": [2480, 1880], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "grey concrete", "gameplay": None},
    {"id": "A079", "text": "wall painted with trees", "px": [2480, 1980], "confidence": "HIGH", "category": "architecture", "geom": None, "visual": "tree mural", "gameplay": None},
    {"id": "A080", "text": "Weird humming in this room", "px": [2580, 1880], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": None, "gameplay": "wiki fluorescent hum; no Entity"},
    {"id": "A081", "text": "Concrete walls, earth floor", "px": [2920, 1880], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "concrete + dirt", "gameplay": None},
    {"id": "A082", "text": "Tiny narrow corridor connects these rooms", "px": [3300, 1880], "confidence": "HIGH", "category": "geometry", "geom": "narrow ~1.5-1.8 m", "visual": None, "gameplay": None},
    {"id": "A083", "text": "Strange sweet smell here - like vanilla. Starts weak but gets more and more intense the longer I stay here", "px": [280, 1980], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": None, "gameplay": "no status effect invented"},
    {"id": "A084", "text": "Mahogany desk - gold pen attached to chain connected to it", "px": [720, 1980], "confidence": "HIGH", "category": "props", "geom": None, "visual": "desk+pen", "gameplay": None},
    {"id": "A085", "text": "It feels like someone was just sitting here", "px": [280, 2180], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": None, "gameplay": "Isolation Effect: no NPC"},
    {"id": "A086", "text": "Largest space I've seen yet - but nothing here", "px": [780, 2280], "confidence": "HIGH", "category": "geometry", "geom": "very large empty hall", "visual": "empty", "gameplay": None},
    {"id": "A087", "text": "Tiny narrow corridor", "px": [180, 2320], "confidence": "HIGH", "category": "geometry", "geom": "narrow passage, dotted unexplored", "visual": None, "gameplay": None},
    {"id": "A088", "text": "Ceiling gets lower and lower until it reaches the floor", "px": [1180, 1980], "confidence": "HIGH", "category": "verticality", "geom": "tapered ceiling to 0", "visual": "wedge", "gameplay": "blocks further travel"},
    {"id": "A089", "text": "Everything goes monochrome in these rooms - even me", "px": [1320, 2080], "confidence": "HIGH", "category": "special_rooms", "geom": "white rooms", "visual": "desaturated/white", "gameplay": "visual only; no player recolor system"},
    {"id": "A090", "text": "foul smell in this room", "px": [1480, 1980], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": None, "gameplay": "no disease invented"},
    {"id": "A091", "text": "Old camp here? Another survivor?", "px": [1380, 2120], "confidence": "HIGH", "category": "props", "geom": "camp remnants", "visual": "sleeping bag/red mark", "gameplay": "Isolation Effect: no living survivor NPC"},
    {"id": "A092", "text": "Office area with pink carpet", "px": [1280, 2320], "confidence": "HIGH", "category": "surface", "geom": "large pink office", "visual": "pink carpet", "gameplay": None},
    {"id": "A093", "text": "Water here is undrinkable", "px": [1760, 2220], "confidence": "HIGH", "category": "water", "geom": "flooded rooms, real water volume", "visual": "dirty/turbid blue", "gameplay": "NOT drinkable; no disease invented"},
    {"id": "A094", "text": "Ceiling too low to pass", "px": [1880, 2120], "confidence": "HIGH", "category": "verticality", "geom": "ceiling ~1.1 m on a flooded arm", "visual": "low", "gameplay": "blocks standing player"},
    {"id": "A095", "text": "Long stairway down", "px": [2080, 1980], "confidence": "HIGH", "category": "verticality", "geom": "long stair flight, local drop, not auto full second floor", "visual": "hatched stair", "gameplay": None},
    {"id": "A096", "text": "room with tiny entrances", "px": [1980, 2020], "confidence": "HIGH", "category": "geometry", "geom": "very small openings", "visual": None, "gameplay": None},
    {"id": "A097", "text": "Theatre?", "px": [2180, 2020], "confidence": "HIGH", "category": "special_rooms", "geom": "tiered/round-ish room", "visual": None, "gameplay": None},
    {"id": "A098", "text": "Boiler room", "px": [2220, 2080], "confidence": "HIGH", "category": "special_rooms", "geom": "small mechanical room", "visual": None, "gameplay": None},
    {"id": "A099", "text": "green carpet area", "px": [2260, 2220], "confidence": "HIGH", "category": "surface", "geom": "green footprint", "visual": "green carpet", "gameplay": None},
    {"id": "A100", "text": "no ceiling - walls rise into darkness", "px": [2320, 2140], "confidence": "HIGH", "category": "verticality", "geom": "omit ceiling; walls extend up ~12 m into void", "visual": "black above", "gameplay": None},
    {"id": "A101", "text": "sounds behind this wall", "px": [2480, 2140], "confidence": "HIGH", "category": "unknown", "geom": "solid wall, no opening", "visual": None, "gameplay": "wiki wall-scratching reports; no Entity"},
    {"id": "A102", "text": "Multiple floors apart, but same carpet. Connected?", "px": [2480, 2240], "confidence": "HIGH", "category": "verticality", "geom": "plan shows split floors with same carpet", "visual": None, "gameplay": "do not auto-merge floors"},
    {"id": "A103", "text": "empty tiled room", "px": [2780, 2140], "confidence": "HIGH", "category": "surface", "geom": "small tiled room", "visual": "tile", "gameplay": None},
    {"id": "A104", "text": "Found satchel and empty notebook here", "px": [2780, 2280], "confidence": "HIGH", "category": "props", "geom": None, "visual": "satchel", "gameplay": "CONTENT_REQUIRED Object; skip pickup in pilot"},
    {"id": "A105", "text": "poor lighting here", "px": [2180, 2380], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "sparse fixtures, one may flicker", "gameplay": None},
    {"id": "A106", "text": "Impassably narrow", "px": [1820, 2360], "confidence": "HIGH", "category": "geometry", "geom": "width < player capsule (~0.64 m)", "visual": "dotted pinch", "gameplay": "cannot pass"},
    {"id": "A107", "text": "Large fan in ceiling", "px": [1860, 2400], "confidence": "HIGH", "category": "architecture", "geom": "ceiling fan in round room", "visual": "fan", "gameplay": None},
    {"id": "A108", "text": "Found wedding ring in this cabinet", "px": [2480, 2420], "confidence": "HIGH", "category": "props", "geom": None, "visual": "cabinet", "gameplay": "CONTENT_REQUIRED"},
    {"id": "A109", "text": "Deep crevice - can't see bottom", "px": [2580, 2460], "confidence": "HIGH", "category": "hazards", "geom": "floor hole / black shaft", "visual": "void", "gameplay": "wiki holes; not an exit"},
    {"id": "A110", "text": "Very dark corridors", "px": [2920, 2460], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "almost no lights", "gameplay": None},
    {"id": "A111", "text": "Painting on wall - shows a man falling through the floor into a yellow room", "px": [3300, 2220], "confidence": "HIGH", "category": "props", "geom": None, "visual": "painting", "gameplay": "not an exit"},
    {"id": "A112", "text": "Stinks of cigarettes", "px": [3520, 2220], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": None, "gameplay": None},
    {"id": "A113", "text": "Lots of exit signs in these halls, but they lead in circles", "px": [3480, 2480], "confidence": "HIGH", "category": "props", "geom": None, "visual": "exit signs", "gameplay": "not a real Exit"},
    {"id": "A114", "text": "Tall ashtray - had a cigarette still smoking", "px": [780, 2580], "confidence": "HIGH", "category": "props", "geom": None, "visual": "ashtray", "gameplay": "Isolation Effect: no person present"},
    {"id": "A115", "text": "I found a shoe here", "px": [1080, 2520], "confidence": "HIGH", "category": "props", "geom": None, "visual": "shoe", "gameplay": None},
    {"id": "A116", "text": "Airvent - I couldn't get the grate off", "px": [980, 2620], "confidence": "HIGH", "category": "architecture", "geom": "vent, not an opening", "visual": "grate", "gameplay": "not an exit"},
    {"id": "A117", "text": "Fake windows - curtains over brick walls", "px": [1280, 2580], "confidence": "HIGH", "category": "architecture", "geom": None, "visual": "curtains/brick", "gameplay": None},
    {"id": "A118", "text": "Dark room", "px": [1280, 2680], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "unlit", "gameplay": None},
    {"id": "A119", "text": "Really huge room blank paper all over floor", "px": [1380, 2780], "confidence": "HIGH", "category": "special_rooms", "geom": "huge pink office floor", "visual": "paper on floor", "gameplay": None},
    {"id": "A120", "text": "Floor slopes down to flooded area", "px": [1880, 2680], "confidence": "HIGH", "category": "verticality", "geom": "ramp down to water", "visual": "grey slope", "gameplay": None},
    {"id": "A121", "text": "Wires all over floor here", "px": [1780, 2780], "confidence": "HIGH", "category": "props", "geom": None, "visual": "wires", "gameplay": None},
    {"id": "A122", "text": "found femur here", "px": [2280, 2480], "confidence": "HIGH", "category": "props", "geom": None, "visual": "bone", "gameplay": "CONTENT_REQUIRED; not an Entity"},
    {"id": "A123", "text": "Room lit by orange emergency bulb", "px": [2180, 2580], "confidence": "HIGH", "category": "lighting", "geom": None, "visual": "single orange light, no fluorescents", "gameplay": None},
    {"id": "A124", "text": "Water filled trough", "px": [1980, 2860], "confidence": "HIGH", "category": "water", "geom": "rectangular water basin", "visual": "dirty water", "gameplay": "not drinkable"},
    {"id": "A125", "text": "Tiny crawlspace: Need to slide through on my belly", "px": [1980, 2920], "confidence": "HIGH", "category": "geometry", "geom": "very low/narrow crawl", "visual": None, "gameplay": "no crouch yet: remains impassable to standing capsule"},
    {"id": "A126", "text": "Pile of books - All filled with gibberish", "px": [2280, 2860], "confidence": "HIGH", "category": "props", "geom": None, "visual": "books", "gameplay": None},
    {"id": "A127", "text": "Sign on wall: \"The End\"", "px": [2420, 2680], "confidence": "HIGH", "category": "props", "geom": None, "visual": "sign", "gameplay": "not an Exit"},
    {"id": "A128", "text": "Leather sofas here - Leather has weird texture, very coarse", "px": [2420, 2580], "confidence": "HIGH", "category": "props", "geom": None, "visual": "sofas", "gameplay": None},
    {"id": "A129", "text": "staircase down", "px": [2480, 2820], "confidence": "HIGH", "category": "verticality", "geom": "long stair flight local drop", "visual": "hatched stair", "gameplay": None},
    {"id": "A130", "text": "Weirdly shaped room", "px": [2580, 2860], "confidence": "HIGH", "category": "geometry", "geom": "keep odd silhouette", "visual": None, "gameplay": None},
    {"id": "A131", "text": "another really long hallway", "px": [2780, 2980], "confidence": "HIGH", "category": "geometry", "geom": "long thin hall", "visual": None, "gameplay": None},
    {"id": "A132", "text": "Felt sicker and sicker the further I went down this passage", "px": [2780, 2620], "confidence": "HIGH", "category": "hazards", "geom": None, "visual": "darker passage", "gameplay": "no sanity drain invented this task"},
    {"id": "A133", "text": "Concave floors", "px": [3020, 2780], "confidence": "HIGH", "category": "verticality", "geom": "dished floor", "visual": None, "gameplay": None},
    {"id": "A134", "text": "Melted rooms - even the wallpaper pattern is smeared", "px": [3480, 2680], "confidence": "HIGH", "category": "architecture", "geom": "warped outline already in trace", "visual": "smeared wallpaper", "gameplay": None},
    {"id": "A135", "text": "Iron gate blocking this hall", "px": [3280, 2920], "confidence": "HIGH", "category": "openings", "geom": "blocked corridor, dotted beyond", "visual": "gate", "gameplay": None},
    {"id": "A136", "text": "Door jammed - frame warped", "px": [1280, 2920], "confidence": "HIGH", "category": "openings", "geom": "unusable door", "visual": "warped", "gameplay": None},
    {"id": "A137", "text": "Floor angles downward strongly - walls are cracked and lights broken", "px": [1320, 3000], "confidence": "HIGH", "category": "verticality", "geom": "tilted floor, broken fixtures", "visual": "cracks", "gameplay": None},
    {"id": "A138", "text": "Same yellow floor as in other area", "px": [1480, 3040], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "standard carpet", "gameplay": None},
    {"id": "A139", "text": "I can hear music playing but can't figure out where it is coming from", "px": [1080, 2920], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": None, "gameplay": "CONTENT_REQUIRED audio later"},
    {"id": "A140", "text": "Square hole - dropped a tile but didn't hear it land", "px": [1180, 3080], "confidence": "HIGH", "category": "hazards", "geom": "floor hole, black shaft", "visual": "void", "gameplay": "wiki holes"},
    {"id": "A141", "text": "Torn wall paper- I got cut when I touched it", "px": [720, 2780], "confidence": "HIGH", "category": "surface", "geom": None, "visual": "torn wallpaper", "gameplay": "no damage system invented"},
    {"id": "A142", "text": "Found sketched map here - nearby rooms are the same, but rooms further away look completely different to the ones I have mapped and passed through", "px": [420, 2680], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": "map prop", "gameplay": "wiki Peripheral Shift compatible; no layout mutation this task"},
    {"id": "A143", "text": "The further I go the less there is", "px": [220, 3180], "confidence": "HIGH", "category": "unknown", "geom": "large empty orange hall", "visual": "empty", "gameplay": None},
    {"id": "A144", "text": "This orange area is completely empty", "px": [620, 3280], "confidence": "HIGH", "category": "geometry", "geom": "empty", "visual": "orange carpet", "gameplay": None},
    {"id": "A145", "text": "Unreachable room through here", "px": [520, 3420], "confidence": "HIGH", "category": "openings", "geom": "visible room, no walkable connection", "visual": "dotted", "gameplay": None},
    {"id": "A146", "text": "Unexplored", "px": [180, 3220], "confidence": "HIGH", "category": "unknown", "geom": "dotted continuation", "visual": None, "gameplay": None},
    {"id": "A147", "text": "These rooms smelt absolutely horrible / is it... a nest?", "px": [780, 3480], "confidence": "HIGH", "category": "unknown", "geom": "cluttered colorful rooms", "visual": "messy", "gameplay": "no Entity nest invented"},
    {"id": "A148", "text": "A cardboard caveman?", "px": [1580, 3380], "confidence": "HIGH", "category": "props", "geom": None, "visual": "cardboard figure", "gameplay": "not an Entity"},
    {"id": "A149", "text": "Worst bed I've ever seen", "px": [1880, 3280], "confidence": "HIGH", "category": "props", "geom": None, "visual": "white bed", "gameplay": None},
    {"id": "A150", "text": "Tally marks scratched into concrete in groups of 7 - total count is 289 Final 2 marks carved nearer ground", "px": [1980, 3120], "confidence": "HIGH", "category": "props", "geom": None, "visual": "tally marks", "gameplay": None},
    {"id": "A151", "text": "Empty shop area", "px": [2100, 3380], "confidence": "HIGH", "category": "special_rooms", "geom": "shop-like", "visual": None, "gameplay": None},
    {"id": "A152", "text": "Fake storefront - \"Hobson and Grieves Printing Ltd.\"", "px": [1980, 3520], "confidence": "HIGH", "category": "architecture", "geom": None, "visual": "storefront facade", "gameplay": None},
    {"id": "A153", "text": "Cupboard stuffed with receipts - all list random items in many currencies", "px": [2480, 3280], "confidence": "HIGH", "category": "props", "geom": None, "visual": "cupboard", "gameplay": None},
    {"id": "A154", "text": "Cistern", "px": [2520, 3380], "confidence": "HIGH", "category": "water", "geom": "cistern volume", "visual": "tank", "gameplay": "not drinkable"},
    {"id": "A155", "text": "Tall concrete room, massive pipe in ceiling", "px": [2380, 3480], "confidence": "HIGH", "category": "architecture", "geom": "tall ceiling + large pipe", "visual": "concrete, pipe", "gameplay": None},
    {"id": "A156", "text": "Extremely long room", "px": [2480, 3620], "confidence": "HIGH", "category": "geometry", "geom": "dotted long continuation south", "visual": None, "gameplay": None},
    {"id": "A157", "text": "The currently mapped areas of the Backrooms 71 days after arrival", "px": [3200, 3500], "confidence": "HIGH", "category": "unknown", "geom": None, "visual": "title, not geometry", "gameplay": None},
    # 17-days-only labels that still describe the same rooms on the master
    {"id": "A158", "text": "unexplored (lights flickering)", "px": [900, 2100], "confidence": "MEDIUM", "category": "lighting", "geom": "from 17-days zoom of same cluster", "visual": "flicker", "gameplay": None},
    {"id": "A159", "text": "Locked door", "px": [1480, 1480], "confidence": "MEDIUM", "category": "openings", "geom": "from 17-days zoom of current-base cluster", "visual": "locked", "gameplay": None},
    {"id": "A160", "text": "water in pipes is unsafe", "px": [2500, 1900], "confidence": "MEDIUM", "category": "water", "geom": "17-days zoom of concrete/tree cluster", "visual": "pipes", "gameplay": "not drinkable"},
    {"id": "A161", "text": "cupboard had a horse skull inside", "px": [2300, 1700], "confidence": "MEDIUM", "category": "props", "geom": "17-days zoom", "visual": "cupboard", "gameplay": "not an Entity"},
    {"id": "A162", "text": "Theoretical interconnected unlit region", "px": [1700, 2100], "confidence": "HIGH", "category": "lighting", "geom": "dashed void between mapped rooms; NOT walkable", "visual": "unlit", "gameplay": "wiki blackout compatible; keep empty"},
]

# ST01 centerline digitized from the hatched "Long stairway down" on
# docs/reference/level-0/level-0-final-map.png (not the A095 annotation pixel).
# Direction: NW (top landing) -> SE (maze T-junction). Arrow on the map points down this flight.
# Width from floor-mask distance transform along the thin hatch (~13.2 px).
ST01_PATH_PX = [
    [2117.4, 1813.6],
    [2120.4, 1819.1],
    [2124.0, 1824.1],
    [2125.6, 1829.4],
    [2128.5, 1833.8],
    [2131.6, 1839.2],
    [2136.1, 1844.9],
    [2138.3, 1850.5],
    [2140.9, 1855.1],
    [2144.0, 1859.1],
    [2146.8, 1864.5],
    [2150.4, 1869.4],
    [2152.6, 1875.2],
    [2155.1, 1879.7],
    [2158.7, 1884.6],
    [2161.1, 1890.2],
    [2164.8, 1895.1],
    [2167.7, 1900.5],
    [2170.4, 1905.9],
    [2173.5, 1911.2],
    [2176.0, 1915.8],
    [2178.9, 1921.0],
    [2181.7, 1925.4],
    [2185.0, 1931.5],
    [2188.2, 1936.9],
]
ST01_WIDTH_PX = 13.18

# ST04 hatch digitized from the striped corridor south of the tall-room cluster
# on level-0-final-map.png (not the A004/ST04 annotation pixel, which sits in charcoal).
# Path west (tall-room mouth) -> east (adjacent beige). Descent 0.8 m.
# Tall-room pocket floor is raised to Y=0.8 so the west mouth meets the flight top.
# SOURCE_APPROXIMATE orientation: map has a label-arrow; descent is out of the tall room.
ST04_PATH_PX = [
    [562.0, 344.0],
    [580.0, 341.0],
    [598.0, 338.5],
    [616.0, 336.0],
]
ST04_WIDTH_PX = 18.0

# SOURCE_APPROXIMATE: wiki/map give no millimetric height.
PARTITION_GAP_H = 2.15  # A003 partitions; ceiling stays 3.0; gap ~0.85 m, not climbable
TALL_ROOM_CEILING_M = 7.0  # A004, within transcribed 6-8 m range
TALL_ROOM_PX_BOX = [500, 150, 648, 318]  # cluster under the tall-room label, north of ST04
POSTER_WALL_PX = [198, 250, 228, 360]  # A002 west wall of the large irregular room (x,z range in px)

STAIRS = [
    {
        "id": "ST01",
        "text": "Long stairway down",
        "px": [2080, 1980],
        "kind": "flight_down",
        "drop_m": 1.5,
        "in_pilot": True,
        "path_px": ST01_PATH_PX,
        "width_px": ST01_WIDTH_PX,
        "y_start": 1.5,
        "y_end": 0.0,
    },
    {"id": "ST02", "text": "staircase down (south-east of The End)", "px": [2480, 2820], "kind": "flight_down", "drop_m": 1.2, "in_pilot": False},
    {"id": "ST03", "text": "house stairs down from lift/house", "px": [780, 720], "kind": "flight_down", "drop_m": 1.0, "in_pilot": False},
    {
        "id": "ST04",
        "text": "NW tall-room stairs",
        "px": [620, 240],
        "kind": "flight_down",
        "drop_m": 0.8,
        "in_pilot": False,
        "path_px": ST04_PATH_PX,
        "width_px": ST04_WIDTH_PX,
        "y_start": 0.8,
        "y_end": 0.0,
    },
    {"id": "ST05", "text": "pool-table stairs", "px": [2480, 360], "kind": "flight", "drop_m": 0.8, "in_pilot": False},
    {"id": "ST06", "text": "non-Euclidean stair cluster", "px": [2100, 180], "kind": "flight", "drop_m": 1.5, "in_pilot": False},
]

ELEVATION = [
    {"id": "E01", "text": "flooded water", "px_box": [1588, 2049, 1920, 2318], "floor_y": -0.30, "in_pilot": True},
    {"id": "E02", "text": "ceiling too low to pass", "px_box": [1840, 2060, 1960, 2180], "ceiling_y": 1.15, "in_pilot": True},
    {"id": "E03", "text": "no ceiling green spur", "px_box": [2280, 2080, 2380, 2200], "ceiling": "none", "wall_height": 12.0, "in_pilot": True},
    {"id": "E04", "text": "poor lighting grey", "px_box": [1980, 2280, 2380, 2580], "lighting": "poor", "in_pilot": True},
    {"id": "E05", "text": "orange emergency room", "px_box": [2100, 2500, 2260, 2640], "lighting": "orange_bulb", "in_pilot": True},
    {"id": "E06", "text": "very tall room (17-days core)", "px_box": [1540, 1640, 1760, 1860], "ceiling_y": 6.5, "in_pilot": False},
    {"id": "E07", "text": "bottomless pool", "px_box": [1290, 1540, 1380, 1630], "hole": True, "in_pilot": False},
]

# 17-days core used as the sole 3D pilot this task.
PILOT = {
    "id": "sector_001",
    "name": "17-days-core",
    "reason": "Central mapped cluster matching the older '17 days after arrival' zoom: flooded water, green carpet, poor lighting, no-ceiling spur, fan, narrow pinch, theatre/boiler/long stair, orange bulb.",
    "px_box": [1550, 1860, 2420, 2580],
}

CANON_CONFLICTS = [
    {
        "id": "C01",
        "topic": "Safe water",
        "map": "bathroom with safe water / Safe water!",
        "wiki": "level-0.md carpets hold mixed unsafe fluids; Almond Water found there is tainted.",
        "resolution": "Implement water geometry only. Do not make it drinkable. Do not restore thirst.",
    },
    {
        "id": "C02",
        "topic": "Red rooms vs wiki Red Rooms",
        "map": "Red rooms / This place makes we feel sick / Tiny red room?",
        "wiki": "red-rooms.md + level-0.md: dangerous disconnected sections, adverse psychology, not meeting places.",
        "resolution": "Keep pink/red geometry. Do not implement Red Room gameplay yet (CONTENT_REQUIRED). Isolation Effect unchanged. Not a multiplayer meeting zone.",
    },
    {
        "id": "C03",
        "topic": "Other people / current base / another survivor",
        "map": "current base, Old camp here? Another survivor?, someone was just sitting here, cigarette still smoking",
        "wiki": "Isolation Effect: two people never find each other except the unimplemented Manila Room.",
        "resolution": "Camp geometry/props allowed. No NPC, no second wanderer, no co-op visibility.",
    },
    {
        "id": "C04",
        "topic": "Windows onto a city / red sun",
        "map": "This whole wall is windows. There's a whole city out there... Why is the sun red?",
        "wiki": "Level 0 is an interior labyrinth; no exterior described.",
        "resolution": "Fake windows only. Do not add an outdoor city skybox as canon exterior.",
    },
    {
        "id": "C05",
        "topic": "Entities",
        "map": "Mannequin, mummified rat, nest?, cardboard caveman, horse skull",
        "wiki": "Level 0 entities unconfirmed.",
        "resolution": "No AI entities. Optional inert props later. Not in this pilot.",
    },
]
